#!/usr/bin/env bash
# the same premise as 4 but elif is used to add additonal if statements
count=1
while [ $count -le 10 ]
do
        if [ $count -eq 4 ]; then
                echo "bad luck"
        elif [ $count -eq 8 ]; then
		echo "good luck"
	else

        echo "Best School"

        fi

        ((count++))
done
