#!/usr/bin/env bash
#same concept as 4 but with extra elif statements and a regular count instead of a repeating phrase
count=1
while [ $count -le 20 ]
do
	if [ $count -eq 4 ]; then
		echo -e "4\nbad luck from China"
	elif [ $count -eq 9 ]; then 
		echo -e "9\nbad luck from Japan"
	elif [ $count -eq 17 ]; then 
		echo -e "17\nbad luck from Italy"
	else
		echo "$count"
	fi
	((count++))
done
