#!/usr/bin/env bash
#use casse to outline multiple lines requiring modifications and now esac plays the role of fi but i still don't really understand the difference
count=1
while [ $count -le 20 ]
do
	case $count in
	4)
		echo -e "4\nbad luck from China"
		;;
	9)
		echo -e "9\nbad luck from Japan"
		;;
	17)
		echo -e "17\nbad luck from Italy"
		;;
	
	*)
		echo "$count"
esac
	((count++))
done
