#!/usr/bin/env bash
# I'm sorry its from chat gpt i couldn't figure this one out
hour=0
minute=1

while [ $hour -le 12 ]
do
  while [ $minute -le 59 ]
  do
   
   printf "%02d:%02d\n" $hour $minute
    
   ((minute++))
  done
  
  minute=0
  ((hour++))
done

